# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hgill.io
email: tech@hgill.io

#write html inside the double quotes to display in jumbotron
description: "<h2>Harry Gill | blog</h2><h4>My dev experiance and thoughts</h4>"



baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hgill.io" # the base hostname & protocol for your site
twitter_username: mygnu_
github_username:  mygnu

# Build settings
markdown: kramdown
